### ISSUE TITLE
Create the first revision of the "Project Plan" deliverable

### ISSUE THREAD

**Issue by JaredDobry** [JaredDobry/enpm613#1]
Collaborate and create the first draft of the Project Plan using the Project Plan and Management Template.
Tabs of the excel document to be completed and reviewed for this iteration are:
- [x] Skills Inventory
- [x] Roles and Responsibilities
- [x] Identification of a "Team Leader"
- [x] Team Operating Procedures
- [x] Project Environment
- [x] Effort Estimation
- [x] Risk Analysis and Management
### Action Items
- [x] Add the Project Plan file to source control
- [x] Document any critical decisions [here](https://github.com/JaredDobry/enpm613/wiki/Project-Decisions)
